// Note: this changes very often. it is accurate as of 2024-03-18.

export interface SharkeyUserMeta {
    maintainerName: string | null;
    maintainerEmail: string | null;
    version: string;
    providesTarball: boolean;
    name: string;
    shortName: string | null;
    uri: string;
    description: string;
    langs: string[];
    tosUrl: string | null;
    repositoryUrl: string | null;
    feedbackUrl: string | null;
    impressumUrl: string | null;
    donationUrl: string | null;
    privacyPolicyUrl: string | null;
    disableRegistration: boolean;
    emailRequiredForSignup: boolean;
    approvalRequiredForSignup: boolean;
    enableHcaptcha: boolean;
    hcaptchaSiteKey: string | null;
    enableMcaptcha: boolean;
    mcaptchaSiteKey: string | null;
    mcaptchaInstanceUrl: null;
    enableRecaptcha: boolean;
    enableAchievements: boolean;
    recaptchaSiteKey: string | null;
    enableTurnstile: boolean;
    turnstileSiteKey: string | null;
    swPublickey: string | null;
    themeColor: string | null;
    mascotImageUrl: string | null;
    bannerUrl: string | null;
    serverErrorImageUrl: string | null;
    notFoundImageUrl: string | null;
    infoImageUrl: string | null;
    iconUrl: string | null;
    backgroundImageUrl: string | null;
    logoImageUrl: string | null;
    maxNoteTextLength: number;
    defaultLightTheme: string | null;
    defaultDarkTheme: string | null;
    defaultLike: string | null;
    ads: string[];
    notesPerOneAd: number;
    enableEmail: boolean;
    enableServiceWorker: boolean;
    translatorAvailable: boolean;
    serverRules: string[];
    mediaProxy: string;
    cacheRemoteFiles: boolean;
    cacheRemoteSensitiveFiles: boolean;
    requireSetup: boolean;
    proxyAccountName: string | null;
    features: {
        localTimeline: boolean;
        globalTimeline: boolean;
        registration: boolean;
        emailRequiredForSignup: boolean;
        hcaptcha: boolean;
        recaptcha: boolean;
        turnstile: boolean;
        objectStorage: boolean;
        serviceWorker: boolean;
        miauth: boolean;
    };
    policies: {
        gtlAvailable: boolean;
        ltlAvailable: boolean;
        btlAvailable: boolean;
        canPublicNote: boolean;
        mentionLimit: number;
        canInvite: boolean;
        inviteLimit: number;
        inviteLimitCycle: number;
        inviteExpirationTime: number;
        canManageCustomEmojis: boolean;
        canManageAvatarDecorations: boolean;
        canSearchNotes: boolean;
        canUseTranslator: boolean;
        canHideAds: boolean;
        driveCapacityMb: number;
        alwaysMarkNsfw: boolean;
        pinLimit: number;
        antennaLimit: number;
        wordMuteLimit: number;
        webhookLimit: number;
        clipLimit: number;
        noteEachClipsLimit: number;
        userListLimit: number;
        userEachUserListsLimit: number;
        rateLimitFactor: number;
        canImportNotes: boolean;
        avatarDecorationLimit: number;
    };
}
