// Note: this changes very often. it is accurate as of 2024-03-18.

export interface SharkeyMeta {
    maintainerName: string | null;
    maintainerEmail: string | null;
    version: string;
    name: string;
    shortName: string | null;
    url: string;
    langs: string[];
    tosUrl: string | null;
    repositoryUrl: string | null;
    feedbackUrl: string | null;
    impressumUrl: string | null;
    donationUrl: string | null;
    privacyPolicyUrl: string | null;
    disableRegistrations: boolean;
    emailRequiredForSignup: boolean;
    approvalRequiredForSignup: boolean;
    enableHcaptcha: boolean;
    hcaptchaSiteKey: string | null;
    enableMcaptcha: boolean;
    mcaptchaSiteKey: string | null;
    enableRecaptcha: boolean;
    recaptchaSiteKey: string | null;
    enableTurnstile: boolean;
    turnstileSiteKey: string | null;
    swPublicKey: string | null;
    themeColor: string | null;
    mascotImageUrl: string | null;
    bannerUrl: string | null;
    serverErrorImageUrl: string | null;
    notFoundImageUrl: string | null;
    infoImageUrl: string | null;
    iconUrl: string | null;
    app192IconUrl: string | null;
    app512IconUrl: string | null;
    backgroundImageUrl: string | null;
    logoImageUrl: string | null;
    defaultLightTheme: string | null;
    defaultDarkTheme: string | null;
    defaultLike: string | null;
    enableEmail: boolean;
    enableServiceWorker: boolean;
    translatorAvailable: boolean;
    cacheRemoteFiles: boolean;
    cacheRemoteSensitiveFiles: boolean;
    pinnedUsers: string[];
    hiddenTags: string[];
    blockedHosts: string[];
    silencedHosts: string[];
    sensitiveWords: string[];
    prohibitedWords: string[];
    preservedUsernames: string[];
    bubbleInstances: string[];
    hcaptchaSecretKey: string | null;
    mcaptchaSecretKey: string | null;
    recaptchaSecretKey: string | null;
    turnstileSecretKey: string | null;
    sensitiveMediaDetection: 'none';
    sensitiveMediaDetectionSensitivity: 'medium';
    setSensitiveFlagAutomatically: boolean;
    enableSensitiveMediaDetectionForVideos: boolean;
    enableBotTrending: boolean;
    proxyAccountId: string | null;
    summalyProxy: string | null;
    email: string | null;
    smtpSecure: boolean;
    smtpHost: string | null;
    smtpUser: string | null;
    smtpPass: string | null;
    swPrivateKey: string | null;
    useObjectStorage: boolean;
    objectStorageBaseUrl: string | null;
    objectStorageBucket: string | null;
    objectStoragePrefix: string | null;
    objectStorageEndpoint: string | null;
    objectStorageRegion: string | null;
    objectStoragePort: number | null;
    objectStorageAccessKey: string | null;
    objectStorageSecretKey: string | null;
    objectStorageUseSSL: boolean;
    objectStorageUseProxy: boolean;
    objectStorageSetPublicRead: boolean;
    objectStorageS3ForcePathStyle: boolean;
    deeplAuthKey: string | null;
    deeplIsPro: boolean;
    deeplFreeMode: boolean;
    deeplFreeInstance: string | null;
    enableIpLogging: boolean;
    enableActiveEmailValidation: boolean;
    enableVerifymailApi: boolean;
    verifymailAuthKey: string | null;
    enableTruemailApi: false;
    truemailInstance: string | null;
    truemailAuthKey: string | null;
    enableChartsForRemoteUser: boolean;
    enableChartsForFederatedInstances: boolean;
    enableServerMachineStats: boolean;
    enableAchievements: boolean;
    enableIdenticonGeneration: boolean;
    bannedEmailDomains: string[];
    policies: Record<string, unknown>;
    manifestJsonOverride: string;
    enableFanoutTimeline: boolean;
    enableFanoutTimelineDbFallback: boolean;
    perLocalUserUserTimelineCacheMax: number;
    perRemoteUserUserTimelineCacheMax: number;
    perUserHomeTimelineCacheMax: number;
    perUserListTimelineCacheMax: number;
    notesPerOneAd: number;
}
